---
# tasks file for ansible-resolv

- name: "[main] Try setting dns to {{ resolv_nameservers }}"
  template: src=resolv.conf.j2 dest=/etc/resolv.conf mode=0644 owner=root group=root
  become: yes
  ignore_errors: yes
  register: resolv_try_result           # failed - file locked and has to be changed OR something wrong.
  tags:
    - resolv

- name: "[main] Check if 'i' file attribute for /etc/resolv.conf is set"
  shell: lsattr /etc/resolv.conf | cut -d ' ' -f 1 | grep -q "i"
  register: resolv_conf_attrib_i  # 0 - 'i' is set; 1 - 'i' is NOT set
  changed_when: false
  failed_when: false
  tags:
    - resolv

- name: "[main] Fail when the previous task's failure is not due to file being locked"
  fail:
    msg: "Something wrong with /etc/resolv.conf. Please check the previous task error message"
  when:
    - resolv_conf_attrib_i.rc == 1
    - resolv_try_result is failed

- name: "[main] Unlock /etc/resolv.conf before changing nameserver, if it was locked"
  command: chattr -i /etc/resolv.conf
  become: yes
  when: resolv_try_result is failed
    or
    not resolv_lock and resolv_conf_attrib_i.rc == 0
  tags:
    - resolv

- name: "[main] Set dns to {{ resolv_nameservers }}"
  template: src=resolv.conf.j2 dest=/etc/resolv.conf mode=0644 owner=root group=root
  become: yes
  when: resolv_try_result is failed
  tags:
    - resolv

- name: "[main] Lock /etc/resolv.conf"
  command: chattr +i /etc/resolv.conf
  become: yes
  when:
    - resolv_lock
    - resolv_try_result is failed or resolv_conf_attrib_i.rc == 1
  tags:
    - resolv
...
